fix: solve int has no isnan()
ibis-project/ibis-ml pull request #154
Opened 2024-09-06 04:35 UTC by jitingxu1

resolve #147

2024-09-10 18:18 UTC, jcrist commented on ibis_ml/steps/_handle_outliers.py
> +                        | table[col_name].isnull()  # noqa: PD003
This is not the correct fix. Instead we'll want to branch on `type().is_floating()` and only call `isnan` for floating inputs.

2024-09-12 22:54 UTC, jitingxu1 commented on ibis_ml/steps/_handle_outliers.py
> +                        | table[col_name].isnull()  # noqa: PD003
Thanks

2024-09-13 02:50 UTC, deepyaman commented on tests/test_handle_outliers.py
> +            "floating_col": [0.0] * 10,  # mean = 0, std = 0 Q1 = 0, Q3 = 0
```suggestion
            "floating_col": [0.0] * 10,  # mean = 0, std = 0, Q1 = 0, Q3 = 0
```

2024-09-13 02:55 UTC, deepyaman requested changes

2024-09-13 02:55 UTC, deepyaman commented on ibis_ml/steps/_handle_outliers.py
> +                        )
```suggestion
                        | (table[col_name].isnull() | table[col_name].type().is_floating() & table[col_name].isnan()) # noqa: PD003
```
seems much simpler, unless I'm missing something?

2024-09-13 04:25 UTC, jitingxu1 commented on ibis_ml/steps/_handle_outliers.py
> +                        )
Yes, it is simpler.

2024-09-13 16:36 UTC, deepyaman approved these changes
:shipit:

2024-09-13 16:36 UTC, merged