fix(steps): add unit test and fix null cols for impute
ibis-project/ibis-ml pull request #157
Opened 2024-09-13 05:43 UTC by jitingxu1

changes:

1. add unit test for _impute.py
2. raise a value error if one column is all NULL, because it does not fulfill users' original goal.

resolve #117

2024-09-13 18:39 UTC, deepyaman requested changes
Left some comments, but maybe more fundamentally—why is this necessary/what motivated it? If somebody wants to fill their missing values with `None`, should I care? E.g. maybe they want to represent all the missing value as NULL (and not NaN), so they do this. Alternatively if you see scikit-learn `SimpleImputer`, they later let the user customize what is considered "missing".

2024-09-13 18:39 UTC, deepyaman commented on tests/test_impute.py
> +    # test _fillna with None
Can you make this a second test, and parametrize with `None` and `NaN` inputs?

2024-09-13 18:39 UTC, deepyaman commented on ibis_ml/steps/_impute.py
> +    if val is None or col.type().is_floating() and math.isnan(val):
```suggestion
    if val is None or and math.isnan(val):
```
Why is the `is_floating()` check necessary?

Also, I think it would make sense to have separate error for `None` and `NaN` (i.e. be specific in the message, rather than saying it could be either)

2024-09-13 19:11 UTC, deepyaman commented
> Left some comments, but maybe more fundamentally—why is this necessary/what motivated it? If somebody wants to fill their missing values with `None`, should I care? E.g. maybe they want to represent all the missing value as NULL (and not NaN), so they do this. Alternatively if you see scikit-learn `SimpleImputer`, they later let the user customize what is considered "missing".

I'm pushing to deprioritize this beyond today, unless you feel it's particularly pressing. Let's focus on getting the other PRs in for release.

2024-09-17 22:41 UTC, jitingxu1 commented on tests/test_impute.py
> +    # test _fillna with None
done

2024-09-17 22:42 UTC, jitingxu1 commented on ibis_ml/steps/_impute.py
> +    if val is None or col.type().is_floating() and math.isnan(val):
It could be a string col, the `math.isnan(val)` will throw an error

2024-09-17 22:43 UTC, jitingxu1 commented
> Left some comments, but maybe more fundamentally—why is this necessary/what motivated it? If somebody wants to fill their missing values with `None`, should I care? E.g. maybe they want to represent all the missing value as NULL (and not NaN), so they do this. Alternatively if you see scikit-learn `SimpleImputer`, they later let the user customize what is considered "missing".

Instead of raise an error, I change it to throw a warning to the user.

2024-09-25 22:59 UTC, merged