style(ruff): clear ruff check violations
ibis-project/ibis-ml pull request #175
Opened 2024-11-22 02:34 UTC by IndexSeek

I was looking through the repo and wanted to clear up the remaining outstanding ruff check violations. 

Many of these are minor, and I was able to clear them by adjusting the following:
```toml
[tool.ruff.lint.per-file-ignores]
"examples/*.ipynb" = ["ERA001", "I001", "T201"]
```

Here are the totals before the run:
```sh
$ ruff check --statistics
17      ERA001  [*] commented-out-code
 8      T201    [*] print
 8      PT001   [*] pytest-fixture-incorrect-parentheses-style
 4      I001    [*] unsorted-imports
 3      RUF100  [*] unused-noqa
 2      E501    [ ] line-too-long
 1      B008    [ ] function-call-in-default-argument
 1      RET504  [*] unnecessary-assign
 1      PTH207  [ ] glob
 1      E721    [ ] type-comparison
 1      UP031   [*] printf-string-formatting
[*] fixable with `ruff check --fix`
```

I'm still getting one violation after this, not sure how to get rid of this one. I might do a bit more digging later on, if this is something we will want to do. Adding `# noqa: E501` wasn't resolving it.

```sh
examples/Using IbisML and DuckDB for a Kaggle competition.ipynb:cell 22:7:89: E501 Line too long (99 > 88)
  |
5 |     Args:
6 |         file_path (str): Path to the file or regex pattern to match files.
7 |         depth (int, optional): Depth of processing. If 1 or 2, additional aggregation is performed.
  |                                                                                         ^^^^^^^^^^^ E501
8 |         is_regex (bool, optional): Whether the file_path is a regex pattern.
  |

Found 1 error.
```

2024-11-23 04:25 UTC, deepyaman commented
Thanks! I'll try and review tomorrow or day after.

2024-11-23 13:59 UTC, IndexSeek commented
> Thanks! I'll try and review tomorrow or day after.

Thank you! There may be some of have been some conflicting with each other from what I found. For example, I was getting violations saying that the `  # noqa: SLF001` was going unused, then after removing, was getting violations running pre-commit that there were [SLF001](https://docs.astral.sh/ruff/rules/private-member-access/#private-member-access-slf001) violations. 

I think these cases are squared away now. 

```sh
$ ruff check
All checks passed!
$ pre-commit run --all-files
prettier.................................................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
Sort __all__ records.....................................................Passed
```

2024-11-25 16:35 UTC, deepyaman requested changes
Thanks! Looks like this caught a number of minor issues and made several net improvements (like the `.glob()` change); much appreciated!

I think the `examples/*.ipynb` skips are fine, but I wonder whether the extra `tests/*.py` ones are necessary?

2024-11-25 16:35 UTC, deepyaman commented on pyproject.toml
> +"tests/*.py" = ["PT001", "RUF100", "SLF001"]
If `SLF001` is coming from the tests, maybe just do `from ibis import _` up top instead?

For `PT001` skip, I think that should be unnecessary with your fixes.

`RUF100` also doesn't seem like it should be necessary.

2024-11-25 16:37 UTC, deepyaman commented
Actually, can you bump the Ruff version in `.pre-commit-config.yaml`? Because Ruff is running in CI, but it's not catching some of these things I assume because of the old version?

2024-11-26 01:02 UTC, IndexSeek commented on pyproject.toml
> +"tests/*.py" = ["PT001", "RUF100", "SLF001"]
Excellent catch! 

Yes, after removing `"tests/*.py" = ["PT001", "RUF100", "SLF001"]`, I am finding that all of the ruff checks are passing without the "tests/*.py" ignores.

2024-11-26 01:13 UTC, IndexSeek commented
> > I'm still getting one violation after this, not sure how to get rid of this one. I might do a bit more digging later on, if this is something we will want to do. Adding `# noqa: E501` wasn't resolving it.
> > ```shell
> > examples/Using IbisML and DuckDB for a Kaggle competition.ipynb:cell 22:7:89: E501 Line too long (99 > 88)
> >   |
> > 5 |     Args:
> > 6 |         file_path (str): Path to the file or regex pattern to match files.
> > 7 |         depth (int, optional): Depth of processing. If 1 or 2, additional aggregation is performed.
> >   |                                                                                         ^^^^^^^^^^^ E501
> > 8 |         is_regex (bool, optional): Whether the file_path is a regex pattern.
> >   |
> > 
> > Found 1 error.
> > ```
> 
> We can just wrap this after "is". :)

🤦 - I should have thought of this! Thank you!

2024-12-01 17:47 UTC, deepyaman approved these changes
This is great, thanks!

2024-12-01 17:48 UTC, merged