feat: polynomial features
ibis-project/ibis-ml pull request #53
Opened 2024-04-03 21:50 UTC by jitingxu1

Add polynomial features

Resolve #41

2024-04-09 18:00 UTC, deepyaman requested changes

2024-04-09 18:00 UTC, deepyaman commented on ibisml/steps/feature_engineering.py
> +                expression *= table[column]
```suggestion
            reduce(operator.mul, [table[c] for c in combination])
```

2024-04-09 18:00 UTC, deepyaman commented on ibisml/steps/feature_engineering.py
> +                expression.name(f"poly_{'_'.join(column for column in combination)}")
Nit: These names may get intractable. Furthermore, it may make sense to not write serial multiplication (e.g. `x * x * x * x * y * y`) when it's just powers (`x**4 * y**2`). Have you seen how other libraries handle this, or any thoughts on it?

I'm OK to do this for now, until people provide feedback wanting something better.

2024-04-09 18:00 UTC, deepyaman commented on ibisml/steps/feature_engineering.py
> +        return table.mutate(**{exp.get_name(): exp for exp in expressions})
```suggestion
        return table.mutate(*expressions)
```
I think this should work, since you already named the expressions.

2024-04-09 18:00 UTC, deepyaman commented on tests/test_feature_engineering.py
> +    assert res.equals(sol)
This is just a structural check; look at how the other tests are written.

2024-04-10 03:03 UTC, jitingxu1 commented on ibisml/steps/feature_engineering.py
> +                expression.name(f"poly_{'_'.join(column for column in combination)}")
Really like this. I will check if there is better way to do this.

2024-04-10 03:05 UTC, jitingxu1 commented on tests/test_feature_engineering.py
> +    assert res.equals(sol)
I thought structure check is enough, I will add some other.

2024-04-10 09:38 UTC, deepyaman commented on tests/test_feature_engineering.py
> +    assert res.equals(sol)
I think a structure check was sufficient for the zero-variance step, because it's clear that it's correct or not if the right columns get dropped. For this, need to verify that the math is also correct.

2024-04-15 21:21 UTC, deepyaman requested changes
Looks good overall, few more small requests...

2024-04-15 21:21 UTC, deepyaman commented on tests/test_feature_engineering.py
> +        )
Can you not use `pandas.testing.assert_frame_equal` instead of rolling your own?

2024-04-15 21:21 UTC, deepyaman commented on tests/test_feature_engineering.py
> +            "poly_y^2": operator.pow(train_table.y, 2),
```suggestion
            "poly_x^2": train_table.x ** 2,
            "poly_x_y": train_table.x * train_table.y,
            "poly_y^2": train_table.y ** 2,
```
Much easier to read. :)

2024-04-15 21:21 UTC, deepyaman commented on ibisml/steps/feature_engineering.py
> +                    operator.pow(table[col], p) if p > 1 else table[col]
```suggestion
                    table[col] ** p if p > 1 else table[col]
```

2024-04-15 21:21 UTC, deepyaman commented on ibisml/steps/feature_engineering.py
> +                    dict(Counter(comb))
```suggestion
                    Counter(comb)
```
Unnecessary cast? Unless you had some specific thoughts around minute space efficiency, but I don't think there's anything important that I see there.

2024-04-16 19:02 UTC, deepyaman commented on tests/test_feature_engineering.py
> +    assert expected.equals(result)
```suggestion
```
I'm going to remove this, since `tm.assert_frame_equal` is already doing structural tests.

2024-04-16 19:03 UTC, deepyaman approved these changes
Thanks for bearing with all the changes! :shipit:

2024-04-16 19:05 UTC, merged