feat(steps): KBinsDiscretizer
ibis-project/ibis-ml pull request #57
Opened 2024-04-09 21:14 UTC by jitingxu1

Added KBinsDiscretizer 
It supports: 
- Uniform strategy: Divides data into bins of equal width based on the minimum and maximum values of each column.
- Quantile strategy: Divides data into bins with an equal number of samples in each bin.

Examples:
```python
import ibis
import ibisml as ml
from ibisml.core import Metadata
ibis.options.interactive = True

p = ibis.examples.penguins.fetch()
step = ml.KBinsDiscretizer(
    ml.numeric(),
    strategy="quantile",
    overwrite=True,
    )
step.fit_table(p, Metadata())
step.transform_table(p)
```

Outputs:
```
┏━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━┓
┃ species ┃ island    ┃ bill_length_mm ┃ bill_depth_mm ┃ flipper_length_mm ┃ body_mass_g ┃ sex    ┃ year ┃
┡━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━┩
│ string  │ string    │ int8           │ int8          │ int8              │ int8        │ string │ int8 │
├─────────┼───────────┼────────────────┼───────────────┼───────────────────┼─────────────┼────────┼──────┤
│ Adelie  │ Torgersen │              1 │             3 │                 0 │           1 │ male   │    0 │
│ Adelie  │ Torgersen │              1 │             2 │                 0 │           1 │ female │    0 │
│ Adelie  │ Torgersen │              1 │             3 │                 2 │           0 │ female │    0 │
│ Adelie  │ Torgersen │           NULL │          NULL │              NULL │        NULL │ NULL   │    0 │
│ Adelie  │ Torgersen │              0 │             4 │                 1 │           0 │ female │    0 │
│ Adelie  │ Torgersen │              1 │             4 │                 1 │           1 │ male   │    0 │
│ Adelie  │ Torgersen │              1 │             2 │                 0 │           1 │ female │    0 │
│ Adelie  │ Torgersen │              1 │             4 │                 2 │           3 │ male   │    0 │
│ Adelie  │ Torgersen │              0 │             3 │                 1 │           0 │ NULL   │    0 │
│ Adelie  │ Torgersen │              1 │             4 │                 1 │           2 │ NULL   │    0 │
│ …       │ …         │              … │             … │                 … │           … │ …      │    … │
└─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┴──────
```

Resolves #44

2024-04-23 23:11 UTC, deepyaman requested changes

2024-04-23 23:11 UTC, deepyaman commented on ibisml/steps/discretization.py
> +                col_name = f"{col_name}_{self.n_bins}_bin_{self.strategy}"
Not big on supporting `overwrite` just for this transformation (similar argument as raising warning just for this). If you don't feel strongly about it, I'd rather leave it out and talk about if we need to support `overwrite`.

(I also don't see it in scikit-learn implementation, and just some `prefix` in Tidymodels Recipes, FWIW.)

2024-04-23 23:11 UTC, deepyaman commented on tests/test_discretization.py
> +def test_KBinsDiscretizer(train_table, test_table, k, strategy):
```suggestion
def test_discretize(train_table, test_table, k, strategy):
```
or something like that, rather than randomly adding camel case here

2024-04-23 23:11 UTC, deepyaman commented on tests/test_discretization.py
> +    assert len(step.bins_edge_) == len(train_table.select(s.of_type("numeric")).columns)
I'd rather see simple examples rather than this complex suite... no idea what this is testing (and too lazy to try, should be easy ;)).

2024-04-24 18:28 UTC, jitingxu1 commented on ibisml/steps/discretization.py
> +            )
I will create an separate issue for this.

2024-04-24 18:31 UTC, jitingxu1 commented on ibisml/steps/discretization.py
> +                col_name = f"{col_name}_{self.n_bins}_bin_{self.strategy}"
make sense to me

2024-04-24 21:08 UTC, merged