feat(examples): add model picker and support torch
ibis-project/ibis-ml pull request #74
Opened 2024-04-26 22:42 UTC by deepyaman

2024-04-29 17:49 UTC, jitingxu1 reviewed
Not sure the name `mod` is the best practice by sklearn. do you mean `model`

<img width="622" alt="image" src="https://github.com/ibis-project/ibis-ml/assets/126802425/78be6c6d-dec4-4860-86dc-0c765067870a">

2024-04-29 18:12 UTC, jitingxu1 requested changes

2024-04-29 18:12 UTC, jitingxu1 commented on ibisml/__init__.py
> +_auto_patch_skorch()
Is this right way to add the sktorch support here? 

1) Looks like it have sktorch dependency even if user does not do model using sktorch.
2) Do we need another `to_torch` method as we planned? To support directly model building using pytroch?

2024-04-30 13:47 UTC, deepyaman commented on ibisml/__init__.py
> +_auto_patch_skorch()
> Looks like it have sktorch dependency even if user does not do model using sktorch.

Good point; let me add a try/except block to ignore `ImportError`.

> Do we need another `to_torch` method as we planned? To support directly model building using pytroch?

`to_torch` exists on Ibis tables already. For the `_auto_patch_skorch`, it's because `y` isn't transformed by an earlier step (most sklearn transformers don't touch it), and `skorch` doesn't support Ibis table as input. XGBoost and sklearn do, because they implement the `__array__` protocol.

I don't believe `to_dmatrix` is actually being used when IbisML recipe + XGBoost model are used in a sklearn pipeline.

For sklearn-compatible estimators used in the sklearn pipeline, unless you change the output format (default: numpy), it will just pass the output as numpy. Then, the estimators support automatically constructive the proper input format (e.g. DMatrix, Torch dataset) from a supported input format, of which numpy is one.

For XGBoost, even if we output `to_dmatrix`, it goes through pandas conversion, since there's no faster path. For Torch, I couldn't find a way to construct Torch from PyArrow, so we could construct from Numpy, which will probably end up being more or less the same as what's happening automatically here. https://github.com/ibis-project/ibis/blob/1926eb40ae4a8aadb4899645745145247636056c/ibis/backends/__init__.py#L337 is the to_torch code, which you can see is nothing special in Ibis.

Maybe there's still value in supporting the `torch` output format, but I don't imagine it will make much difference.

2024-04-30 13:50 UTC, deepyaman commented on ibisml/__init__.py
> +_auto_patch_skorch()
My first attempt was patching `to_numpy` in `skorch`. However, copying what I wrote previously to @jcrist:

> It seems patching `to_numpy` is woefully insufficient; there's a lot of logic in `skorch` that depends on the input being in one of a set of formats (i.e. not Ibis).
> 
> I guess `Recipe.set_output(transform="pandas")` also doesn't do anything to solve the issue, because y has not been used/output yet? (I did try, error on the same path.)

I can try to open an issue on `skorch` to support any input implementing the `__array__` protocol, as a longer-term solution.

2024-04-30 14:13 UTC, deepyaman commented
> Not sure the name `mod` is the best practice by sklearn. do you mean `model`
> 
> <img alt="image" width="622" src="https://private-user-images.githubusercontent.com/126802425/326535318-78be6c6d-dec4-4860-86dc-0c765067870a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODY1OTUsIm5iZiI6MTcxNDQ4NjI5NSwicGF0aCI6Ii8xMjY4MDI0MjUvMzI2NTM1MzE4LTc4YmU2YzZkLWRlYzQtNDg2MC04NmRjLTBjNzY1MDY3ODcwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNDExMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjc0YTU5OGQ5Mzc3MTU3YzY1ODRkYzUzZGY1OWFiMjBhODkyNDU4N2RmYzc4YmFkMGRlZTQ4ZmRiMDhiMGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L0AekuA-heCm3u4xBpfZtOaKvGdx20jYRcxhvTy-4ms">

Mostly copied names and such from https://www.tidymodels.org/start/recipes/ (the tutorial that this more-or-less replicates). They had `lr_mod`, so I changed it to `mod` when I didn't just have the linear regression, but I'm pretty flexible on this. :shrug: Is `model` more commonly used in sklearn examples?

2024-04-30 23:12 UTC, jitingxu1 commented
Is it a good way to do this support by setting the output format here for different model handoff? 
https://github.com/ibis-project/ibis-ml/blob/main/ibisml/core.py#L323C70-L323C74

2024-05-01 00:04 UTC, deepyaman commented
> Is it a good way to do this support by setting the output format here for different model handoff? https://github.com/ibis-project/ibis-ml/blob/main/ibisml/core.py#L323C70-L323C74

To be honest, I'm not sure. This is meant to be compatible with the scikit-learn API; however, I'm not sure how effective options that are not supported by scikit-learn really are (e.g. PyArrow in the current implementation). https://scikit-learn.org/stable/modules/generated/sklearn.base.TransformerMixin.html#sklearn.base.TransformerMixin.set_output lists the options that scikit-learn supports.

Beyond that, I'm not sure how useful having another output format would be, even if it fit the scikit-learn model cleanly. For example, a "dmatrix" or "torch" output option would likely go through pandas/numpy anyway, so there's not much to be gained at this time? Maybe if they support more direct PyArrow-to-{format} conversion in the future.

Last but not least, this wouldn't help avoid the `_auto_patch_skorch` code; that is a workaround to the fact that `y` is still an `ibis.expr.types.Column` (not supported by `skorch`), since `y` doesn't get transformed by the first recipe. `X` is already transformed to numpy, since most of the scikit-learn transform steps only affect `X`.

2024-05-01 01:02 UTC, merged